version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/kompiler-plugin
    steps:
      - checkout
      - run: ./gradlew dependencies
      - run: ./gradlew build
      - store_test_results:
          path: ~/kompiler-plugin/kompiler-core/build/test-results
